package net.itskittyyoutube.kitty;

import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.registry.FlammableBlockRegistry;
import net.itskittyyoutube.kitty.block.TBSBlocks;
import net.itskittyyoutube.kitty.item.TBSItems;
import net.itskittyyoutube.kitty.sounds.TBSSoundEvents;
import net.itskittyyoutube.kitty.tab.TBSCreativeTabs;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TBS implements ModInitializer {
	public static final String MOD_ID = "kitty";
	public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);
    public static final boolean DEBUG_MODE = false;

	@Override
	public void onInitialize() {
        TBSItems.registerItems();
        TBSSoundEvents.registerSoundEvents();
        TBSCreativeTabs.registerTabs();
        TBSBlocks.registerBlocks();

        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.PLANKS_TEMPLATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.WHITE_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.LIGHT_GRAY_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.GRAY_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.BLACK_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.BROWN_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.RED_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.ORANGE_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.YELLOW_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.LIME_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.GREEN_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.CYAN_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.LIGHT_BLUE_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.BLUE_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.PURPLE_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.MAGENTA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.PINK_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.WHITE_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.LIGHT_GRAY_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.GRAY_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.BLACK_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.BROWN_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.RED_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.ORANGE_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.YELLOW_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.LIME_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.GREEN_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.CYAN_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.LIGHT_BLUE_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.BLUE_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.PURPLE_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.MAGENTA_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.PINK_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.WHITE_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.LIGHT_GRAY_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.GRAY_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.BLACK_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.BROWN_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.RED_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.ORANGE_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.YELLOW_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.LIME_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.GREEN_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.CYAN_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.LIGHT_BLUE_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.BLUE_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.PURPLE_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.MAGENTA_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.PINK_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.WHITE_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.LIGHT_GRAY_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.GRAY_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.BLACK_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.BROWN_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.RED_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.ORANGE_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.YELLOW_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.LIME_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.GREEN_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.CYAN_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.LIGHT_BLUE_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.BLUE_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.PURPLE_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.MAGENTA_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.PINK_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.WHITE_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.LIGHT_GRAY_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.GRAY_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.BLACK_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.BROWN_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.RED_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.ORANGE_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.YELLOW_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.LIME_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.GREEN_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.CYAN_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.LIGHT_BLUE_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.BLUE_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.PURPLE_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.MAGENTA_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.PINK_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.CHERRY_BIRCH_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.CHERRY_BIRCH_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.STRIPPED_CHERRY_BIRCH_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.STRIPPED_CHERRY_BIRCH_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.CHERRY_BIRCH_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.CHERRY_BIRCH_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.CHERRY_BIRCH_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.CHERRY_BIRCH_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.CHERRY_BIRCH_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.CHERRY_BIRCH_LEAVES, 30, 60);
        //FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.SHELFSHELF, 30, 20);
        //FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.SHELFSHELF, 30, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.GOLDEN_BIRCH_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.GOLDEN_BIRCH_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.STRIPPED_GOLDEN_BIRCH_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.STRIPPED_GOLDEN_BIRCH_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.GOLDEN_BIRCH_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.GOLDEN_BIRCH_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.GOLDEN_BIRCH_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.GOLDEN_BIRCH_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.GOLDEN_BIRCH_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TBSBlocks.GOLDEN_BIRCH_LEAVES, 30, 60);
    }
}
